<section>
    <div class="container">
        <div style="padding-top: 1.5em; padding-bottom: 1.5em;">
            <a href="p_register" class="btn btn-warning btn-user btn-block">
                Ajouter un Produit
            </a>
        </div>
        <?php
            if (isset($_SESSION["delete_alert"])){
                echo ($_SESSION['delete_alert']);
            }
            if (isset($_SESSION["update_alert"])){
                echo ($_SESSION['update_alert']);
            }
        ?>
        <?php
            $model = new dbConnect('root', '', 'coiffure');
            $model->productList();
        ?>
    </div>
    <?php
        if (isset($_SESSION["delete_alert"])){
            unset($_SESSION["delete_alert"]);
        }
        if (isset($_SESSION["update_alert"])){
            unset($_SESSION["update_alert"]);
        }
    ?>
    
</section>