<link rel="stylesheet" href="./assets/css/contact.css">
<title>Contact Form #6</title>
<script nonce="3a79c6f1-04b5-40bb-a3c2-2860e7a73650">
    (function(w, d) {
        ! function(e, f, g, h) {
            e.zarazData = e.zarazData || {};
            e.zarazData.executed = [];
            e.zaraz = {
                deferred: [],
                listeners: []
            };
            e.zaraz.q = [];
            e.zaraz._f = function(i) {
                return function() {
                    var j = Array.prototype.slice.call(arguments);
                    e.zaraz.q.push({
                        m: i,
                        a: j
                    })
                }
            };
            for (const k of ["track", "set", "debug"]) e.zaraz[k] = e.zaraz._f(k);
            e.zaraz.init = () => {
                var l = f.getElementsByTagName(h)[0],
                    m = f.createElement(h),
                    n = f.getElementsByTagName("title")[0];
                n && (e.zarazData.t = f.getElementsByTagName("title")[0].text);
                e.zarazData.x = Math.random();
                e.zarazData.w = e.screen.width;
                e.zarazData.h = e.screen.height;
                e.zarazData.j = e.innerHeight;
                e.zarazData.e = e.innerWidth;
                e.zarazData.l = e.location.href;
                e.zarazData.r = f.referrer;
                e.zarazData.k = e.screen.colorDepth;
                e.zarazData.n = f.characterSet;
                e.zarazData.o = (new Date).getTimezoneOffset();
                if (e.dataLayer)
                    for (const r of Object.entries(Object.entries(dataLayer).reduce(((s, t) => ({
                            ...s[1],
                            ...t[1]
                        }))))) zaraz.set(r[0], r[1], {
                        scope: "page"
                    });
                e.zarazData.q = [];
                for (; e.zaraz.q.length;) {
                    const u = e.zaraz.q.shift();
                    e.zarazData.q.push(u)
                }
                m.defer = !0;
                for (const v of [localStorage, sessionStorage]) Object.keys(v || {}).filter((x => x.startsWith("_zaraz_"))).forEach((w => {
                    try {
                        e.zarazData["z_" + w.slice(7)] = JSON.parse(v.getItem(w))
                    } catch {
                        e.zarazData["z_" + w.slice(7)] = v.getItem(w)
                    }
                }));
                m.referrerPolicy = "origin";
                m.src = "/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(e.zarazData)));
                l.parentNode.insertBefore(m, l)
            };
            ["complete", "interactive"].includes(f.readyState) ? zaraz.init() : e.addEventListener("DOMContentLoaded", zaraz.init)
        }(w, d, 0, "script");
    })(window, document);
</script>
</head>

<body>
    <div class="content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <h3 class="heading mb-4">Let's talk about everything!</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas debitis, fugit natus?</p>
                            <p><img src="./assets/img/contact/coiffure.jpg" alt="Image" class="img-fluid"></p>
                        </div>
                        <div class="col-md-6">
                            <form class="mb-5" method="post" id="contactForm" name="contactForm">
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <input type="text" class="form-control" name="name" id="name" placeholder="Your name">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <input type="text" class="form-control" name="email" id="email" placeholder="Email">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <textarea class="form-control" name="message" id="message" cols="30" rows="7" placeholder="Write your message"></textarea>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <input type="submit" value="Send Message" class="btn btn-primary rounded-0 py-2 px-4">
                                        <span class="submitting"></span>
                                    </div>
                                </div>
                            </form>
                            <div id="form-message-warning mt-4"></div>
                            <div id="form-message-success">
                                Your message was sent, thank you!
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>