<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="Fondex – Business &amp; Finance Consulting HTML Template" />
    <meta name="author" content="https://www.themetechmount.com/" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <title><?= $title; ?></title>

    <!-- favicon icon -->
    <link rel="shortcut icon" href="./assets/images/favicon.png" />

    <!-- bootstrap -->
    <link rel="stylesheet" type="text/css" href="./assets/css/bootstrap.min.css" />

    <!-- animate -->
    <link rel="stylesheet" type="text/css" href="./assets/css/animate.css" />

    <!-- owl-carousel -->
    <link rel="stylesheet" type="text/css" href="./assets/css/owl.carousel.css">

    <!-- themify -->
    <link rel="stylesheet" type="text/css" href="./assets/css/themify-icons.css" />

    <!-- flaticon -->
    <link rel="stylesheet" type="text/css" href="./assets/css/flaticon.css" />


    <!-- REVOLUTION LAYERS STYLES -->

    <link rel="stylesheet" type="text/css" href="./assets/revolution/css/layers.css">

    <link rel="stylesheet" type="text/css" href="./assets/revolution/css/settings.css">

    <!-- prettyphoto -->
    <link rel="stylesheet" type="text/css" href="./assets/css/prettyPhoto.css">

    <!-- shortcodes -->
    <link rel="stylesheet" type="text/css" href="./assets/css/shortcodes.css" />

    <!-- main -->
    <link rel="stylesheet" type="text/css" href="./assets/css/main.css" />

    <!-- responsive -->
    <link rel="stylesheet" type="text/css" href="./assets/css/responsive.css" />

    <!-- styles  -->
    <link rel="stylesheet" href="./assets/css/produits.css">

    <!-- services -->

    <link rel="stylesheet" href="./assets/css/services.css">

</head>

<body>

    <!--page start-->
    <div class="page">

        <!--header start-->
        <header id="masthead" class="header ttm-header-style-classic">

            <!-- ttm-header-wrap -->
            <div class="ttm-header-wrap" style="background-color: #FFCD61">
                <!-- ttm-stickable-header-w -->
                <div id="ttm-stickable-header-w" class="ttm-stickable-header-w clearfix">
                    <div id="site-header-menu" class="site-header-menu">
                        <div class="site-header-menu-inner ttm-stickable-header">
                            <div class="container" style="background-color: #FFCD61">
                                <!-- site-branding -->
                                <div class="site-branding" style="background-color: #FFCD61" >
                                    <a class="home-link" href="index.html" title="Fondex" rel="home">
                                        <img id="logo-img" class="img-center" src="./assets/images/logo.png" alt="logo-img" style="width: 250px; height: 200px;">
                                    </a>

                                </div><!-- site-branding end -->
                                <!--site-navigation -->
                                <div id="site-navigation" class="site-navigation">
                                    <div class="ttm-menu-toggle">
                                        <input type="checkbox" id="menu-toggle-form" />
                                        <label for="menu-toggle-form" class="ttm-menu-toggle-block">
                                            <span class="toggle-block toggle-blocks-1"></span>
                                            <span class="toggle-block toggle-blocks-2"></span>
                                            <span class="toggle-block toggle-blocks-3"></span>
                                        </label>
                                    </div>
                                    <nav id="menu" class="menu" style="background-color: #FFCD61;">
                                        <ul class="dropdown">
                                            
                                            <li >
                                                <a href="home">Accueil</a>
                                            </li>
                                            <li>
                                                <a href="#produit">Produits</a>
                                            </li>
                                            <li>
                                                <a href="#services">Services</a>
                                            </li>
                                            <li>
                                                <a href="contact">Contact</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                                                    <i class="fa-solid fa-user" style="color: black;"></i>
                                                </a>
                                                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                                                    <div class="bg-white py-2 collapse-inner rounded">
                                                        <h6 class="collapse-header">Users board</h6>
                                                        <?php 
                                                        if (!isset($_SESSION["user"])){
                                                            echo ("<a class='collapse-item' style='color: black; padding: 0.5em;' href='login'>Login</a>");
                                                            echo ("<a class='collapse-item' style='color: black; padding: 0.5em;' href='register'>Register</a>");
                                                        }
                                                        else {
                                                            if ($_SESSION['user']['0']['role'] == 1){
                                                                echo ("<a class='collapse-item' style='color: black; padding: 0.5em;' href='admin'>Admin</a>");
                                                            }
                                                            echo ("<a class='collapse-item' style='color: black; padding: 0.5em;' href='logout'>Déconnexion</a>");
                                                        }
                                                        ?>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </nav>
                                </div><!-- site-navigation end-->
                            </div>
                        </div>
                    </div>
                </div><!-- ttm-stickable-header-w end-->
            </div>
            <!--ttm-header-wrap end -->
        </header>
        <!--header end-->