<!--footer start-->
<footer class="footer widget-footer clearfix">
    <div class="first-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="first-footer-inner">
                        <div class="footer-logo">
                            <img id="footer-logo-img" class="img-center" src="./assets/images/logo.png" alt="">
                        </div>
                        <div class="row no-gutters footer-box">
                            <div class="col-md-4 widget-area">
                                <div class="featured-box text-center">
                                    <div class="featured-content">
                                        <div class="featured-title">
                                            <h5>Notre adresse</h5>
                                        </div>
                                        <div class="featured-desc">
                                            <p>Quartier ou jsp quoi</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 widget-area">
                                <div class="featured-box text-center">
                                    <div class="featured-content">
                                        <div class="featured-title">
                                            <h5>Talk To Expert</h5>
                                        </div>
                                        <div class="featured-desc">
                                            <p>+XXXX XXX XXX XXXX XX</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 widget-area">
                                <div class="featured-box text-center">
                                    <div class="featured-content">
                                        <div class="featured-title">
                                            <h5>Envoyez nous un mail</h5>
                                        </div>
                                        <div class="featured-desc">
                                            <p>example@yourdomain.com</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="second-footer ttm-textcolor-white">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3 widget-area">
                    <div class="widget widget_text  clearfix">
                        <h3 class="widget-title">Notre business</h3>
                        <div class="textwidget widget-text">
                        En tant que consultant commercial, nous nous concentrons sur la fourniture de résultats quantifiables pour nos clients, basés sur une méthodologie éprouvée et une solide expérience.
                            <br><br>
                            <div class="social-icons circle social-hover">
                                <ul class="list-inline">
                                    <li class="social-facebook"><a class="tooltip-top" target="_blank" href="#" data-tooltip="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                    <li class="social-instagram"><a class="tooltip-top" target="_blank" href="#" data-tooltip="Instagram"><i class="fa-brands fa-instagram"></i></a></li>
                                    <li class="social-whatsapp"><a class=" tooltip-top" target="_blank" href="" data-tooltip="Whatsapp"><i class="fa-brands fa-whatsapp"></i></a></li>
                                </ul>
                            </div>
                            <br>
                            <div class="mb-20">
                                <a class="ttm-btn ttm-btn-size-xs ttm-btn-shape-square ttm-btn-style-fill ttm-btn-bgcolor-skincolor ttm-btn-color-white" href="#">READ MORE</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3 widget-area">
                    <div class="widget widget_nav_menu clearfix">
                        <h3 class="widget-title">Liens rapide</h3>
                        <ul id="menu-footer-services">
                            <li><a href="#">Prendre rendez-vous</a></li>
                            <li><a href="#">Services clients</a></li>
                            <li><a href="#">Department Services</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3 widget-area">
                    <div class="widget flicker_widget clearfix">
                        <h3 class="widget-title">Nos sites</h3>
                        <div class="textwidget widget-text">
                            <img src="./assets/images/map-footer.png" class="img-fluid" alt="map-footer">
                            <br>
                            <br>
                            <ul class="ttm-our-location-list">
                                <li><i class="fa fa-map-marker"></i>Abidjan: xxx-xxx-xx-x</li>
                                <li><i class="fa fa-map-marker"></i>Yamoussokro: xxx-xxx-xx-x</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom-footer-text ttm-textcolor-white">
        <div class="container">
            <div class="row copyright">
                <div class="col-md-12">
                    <div class="">
                        <span>Copyright © 2022&nbsp;<a href="#">Nexus Legacy</a>. All rights reserved.</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <ul id="menu-footer-menu" class="footer-nav-menu">
                        <li><a href="produits">Produits</a></li>
                        <li><a href="services">Services</a></li>
                        <li><a href="contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--footer end-->

<!--back-to-top start-->
<a id="totop" href="#top">
    <i class="fa fa-angle-up"></i>
</a>
<!--back-to-top end-->

</div><!-- page end -->


<!-- Javascript -->

<script src="./assets/js/jquery.min.js"></script>
<!-- Sm jq --><script src="./assets/js/jquery.redirect.js"></script>
<script src="./assets/js/tether.min.js"></script>
<script src="./assets/js/bootstrap.min.js"></script>
<script src="./assets/js/jquery.easing.js"></script>
<script src="./assets/js/jquery-waypoints.js"></script>
<script src="./assets/js/jquery-validate.js"></script>
<script src="./assets/js/owl.carousel.js"></script>
<script src="./assets/js/jquery.prettyPhoto.js"></script>
<script src="./assets/js/numinate.min.js?ver=4.9.3"></script>
<script src="./assets/js/main.js"></script>
<script src="./assets/js/chart.js"></script>

<!-- Sam -->
<script src="./assets/js/update_delete.js"></script>

<!-- Revolution Slider -->
<script src="./assets/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="./assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="./assets/revolution/js/slider.js"></script>


<!-- SLIDER REVOLUTION 5.0 EXTENSIONS  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->

<!-- fontawesome -->
<script src="https://kit.fontawesome.com/72c4965b41.js" crossorigin="anonymous"></script>
<script src="./assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="./assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="./assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="./assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="./assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="./assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="./assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="./assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>

<!-- Javascript end-->

</body>

</html>