<!-- link lulux ! -->



<!-- link lulux !  END -->


<section class="vh-100" style="background-color:#0DA612;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src=" ./assets/images/coiffure-bg.png" alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">
                                <?php if (isset($_SESSION['flash_data']) && $_SESSION['flash_data'] == "success") : ?>
                                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                                        <?= (isset($_SESSION["message"])) ? $_SESSION["message"] : ""; ?>
                                    </div>
                                <?php elseif (isset($_SESSION['flash_data']) && $_SESSION['flash_data'] == "error") : ?>
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        <?= (isset($_SESSION["message"])) ? $_SESSION["message"] : ""; ?>
                                    </div>
                                <?php endif; ?>
                                <form action="signin" method="POST">

                                    <div class="d-flex align-items-center mb-3 pb-1">
                                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                                        <span class="h1 fw-bold mb-0">ABIDJANAISE </span>
                                    </div>

                                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Connectez vous a votre compte </h5>

                                    <div class="form-outline mb-4">
                                        <input type="email" id="form2Example17" class="form-control form-control-lg" name="inputEmail"/>
                                        <label class="form-label" for="form2Example17">Email</label>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input type="password" id="form2Example27" class="form-control form-control-lg" name="inputPassword"/>
                                        <label class="form-label" for="form2Example27">Mots de passe</label>
                                    </div>

                                    <div class="pt-1 mb-4">
                                        <button class="btn  btn-lg btn-block" style="background-color: #F98808;" type="submit" name="signin">Connexion</button>
                                    </div>

                                    <a class="small text-muted" href="forgot">Mots de passe oublié ?</a>

                                    </br>

                                    <a href="#!" class="small text-muted">Disegner Par Nexus Legacy</a>

                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
        if (isset($_SESSION['flash_data'])) {
            unset($_SESSION["flash_data"]);
            unset($_SESSION["message"]);
        }
        ?>
    </div>
</section>