<section class="row w-100">
    <div class="col-lg-6 col-img"></div>
    <div class="col-lg-6">
        <div class="container">
            <div class="row">
                <div class="col-md-10 offset-md-1">
                    <h6 class="text-warning">PRODUITS</h6>
                    <h1>NOS PRODUITS</h1>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                        Nihil dolor consectetur veniam laudantium ut. Temporibus
                        itaque iste fugit dolore exercitationem a, distinctio
                        quis, reprehenderit vel libero facilis odio aspernatur non!
                    </p>

                    <div class="feature d-flex mt-5">
                        <div class="icon me-3">
                            <i class="fa-solid fa-2x fa-face-smile-wink"></i>
                        </div>
                        <div class="mx-2">
                            <h5>Bonne humeur !</h5>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                            </p>
                        </div>
                    </div>

                    <div class="feature d-flex mt-5">
                        <div class="icon me-3">
                            <i class="fa-solid fa-2x fa-face-smile-wink"></i>
                        </div>
                        <div class="mx-2">
                            <h5>Options</h5>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                            </p>
                        </div>
                    </div>

                    <div class="feature d-flex mt-5">
                        <div class="icon me-3">
                            <i class="fa-solid fa-2x fa-face-smile-wink"></i>
                        </div>
                        <div class="mx-2">
                            <h5>Options</h5>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

<section>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 
 
 
 <!-- Bootstrap CSS -->
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="./assets/css/carroussel.css">
<title>Bootstrap Carousel Product Slider Example</title>


<body class="bg-light">

 
<div class="container">
<div class="col-xl-12">
<h2 class="text-center text-black">Carousel 4 Column Product Slider</h2>
</div>

    <div id="carouselFourColumn" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <?php
        $model = new dbConnect('root', '', 'coiffure');
        $model->productCarouselIndicators();
        ?>
      </ol>
      <div class="carousel-inner">
        <?php
          
          $model->productCarousel();
        ?>
      </div>
      <a class="carousel-control-prev" href="#carouselFourColumn" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselFourColumn" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    </div>	
    <?php $model->productModal(); ?>


</section>


    