<section class="row w-100">
    <div class="col-lg-6 col-img"></div>
    <div class="col-lg-6">
        <div class="container">
            <div class="row">
                <div class="col-md-10 offset-md-1">
                    <h6 class="text-warning">PRODUITS</h6>
                    <h1>NOS PRODUITS</h1>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                        Nihil dolor consectetur veniam laudantium ut. Temporibus
                        itaque iste fugit dolore exercitationem a, distinctio
                        quis, reprehenderit vel libero facilis odio aspernatur non!
                    </p>

                    <div class="feature d-flex mt-5">
                        <div class="icon me-3">
                            <i class="fa-solid fa-2x fa-face-smile-wink"></i>
                        </div>
                        <div>
                            <h5>Bonne humeur !</h5>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                            </p>
                        </div>
                    </div>

                    <div class="feature d-flex mt-5">
                        <div class="icon me-3">
                            <i class="fa-solid fa-2x fa-face-smile-wink"></i>
                        </div>
                        <div>
                            <h5>Options</h5>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                            </p>
                        </div>
                    </div>

                    <div class="feature d-flex mt-5">
                        <div class="icon me-3">
                            <i class="fa-solid fa-2x fa-face-smile-wink"></i>
                        </div>
                        <div>
                            <h5>Options</h5>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

<section>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 
 
 
 <!-- Bootstrap CSS -->
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="./assets/css/carroussel.css">
<title>Bootstrap Carousel Product Slider Example</title>


<body class="bg-light">

 
<div class="container">
<div class="col-xl-12">
<h2 class="text-center text-black">Carousel 4 Column Product Slider</h2>
</div>

    <div id="carouselFourColumn" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselFourColumn" data-slide-to="0" class="active"></li>
        <li data-target="#carouselFourColumn" data-slide-to="1"></li>
        <li data-target="#carouselFourColumn" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <?php
          $model = new dbConnect('root', '', 'coiffure');
          $model->productCarousel();
        ?>
      </div>
      <a class="carousel-control-prev" href="#carouselFourColumn" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselFourColumn" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    </div>	


 
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>





</section>


<div>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="./assets/css/bootstrap.min.css">
    
    <!-- Style -->
    <link rel="stylesheet" href="./assets/css/services.css">

    <title>Modal #8</title>
  </head>
  <body>
    

    <style>
    .img-fluid{
             width : 400px;
             padding: 0px;
             
    }

    .row1{
      display: grid;

  
     
  grid-template-columns: repeat(2, 1fr);
    }
    .col-12 {
      
    }
  
    </style>


    <div class="container content">
          <div class="row1 align-items-center content">

                  <div class="col-12 text-center">
                    
                    <img src="./assets/images/portfolio/01.jpg" alt="Image" class="img-fluid" style="background-color: #b2fcff;"  data-toggle="modal" data-target="#exampleModalCenter">

                        </div>

                  <div class="col-12 text-center">
                    
                    <img src="./assets/images/portfolio/01.jpg"  alt="Image" class="img-fluid" style="background-color: #b2fcff;"  data-toggle="modal" data-target="#exampleModalCenter">

                    </div>

                  <div class="col-12 text-center ">
                    
                    <img src="./assets/images/portfolio/01.jpg"  alt="Image" class="img-fluid" style="background-color: #b2fcff;"  data-toggle="modal" data-target="#exampleModalCenter">

                </div>

                  <div class="col-12 text-center ">
                    
                    <img src="./assets/images/portfolio/01.jpg" alt="Image" class="img-fluid" style="background-color: #b2fcff;"  data-toggle="modal" data-target="#exampleModalCenter">

            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-md  modal-dialog-centered" role="document">
        <div class="modal-content rounded-0">
          <div class="modal-body py-0">

            
            <div class="d-block main-content">
              <img src="images/undraw_updated_rr85.svg" alt="Image" class="img-fluid" style="background-color: #b2fcff;">
              <div class="content-text p-4">
                
                <h3 class="mb-4">Introducing Work from Anywhere</h3>
                <p class="mb-4">All their equipment and instruments are alive. The sky was this is cloudless and of a deep dark blue. A shining crescent far beneath the flying vessel.</p>
                <div class="d-flex">
                  <div class="ml-auto">
                    <a href="#" class="btn btn-link" data-dismiss="modal">No thanks</a>
                    <a href="#" class="btn btn-primary px-4">Get the app</a>
</div>
<!-- Portfolio item 6 modal popup-->
<div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="close-modal" data-bs-dismiss="modal"><img src="assets/img/close-icon.svg" alt="Close modal" /></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="modal-body">
                            <!-- Project details-->
                            <h2 class="text-uppercase">Project Name</h2>
                            <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                            <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/6.jpg" alt="..." />
                            <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
                            <ul class="list-inline">
                                <li>
                                    <strong>Client:</strong>
                                    Window
                                </li>
                                <li>
                                    <strong>Category:</strong>
                                    Photography
                                </li>
                            </ul>
                            <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                <i class="fas fa-xmark me-1"></i>
                                Close Project
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>



</div>
