
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="./assets/css/bootstrap.min.css">
    
    <!-- Style -->
    <link rel="stylesheet" href="./assets/css/services.css">

    <title>Modal #8</title>
  </head>
  <body>
    

    <style>
    .img-fluid{
             width : 400px;
             padding: 0px;
             
    }

    .row{
      display: grid;

  
     
  grid-template-columns: repeat(2, 1fr);
    }
    .col-12 {
      
    }
  
    </style>


    <div class="container content">
          <div class="row align-items-center content">

                  <div class="col-12 text-center">
                    
                    <img src="./assets/images/portfolio/01.jpg" alt="Image" class="img-fluid" style="background-color: #b2fcff;"  data-toggle="modal" data-target="#exampleModalCenter">

                        </div>

                  <div class="col-12 text-center">
                    
                    <img src="./assets/images/portfolio/01.jpg"  alt="Image" class="img-fluid" style="background-color: #b2fcff;"  data-toggle="modal" data-target="#exampleModalCenter">

                    </div>

                  <div class="col-12 text-center ">
                    
                    <img src="./assets/images/portfolio/01.jpg"  alt="Image" class="img-fluid" style="background-color: #b2fcff;"  data-toggle="modal" data-target="#exampleModalCenter">

                </div>

                  <div class="col-12 text-center ">
                    
                    <img src="./assets/images/portfolio/01.jpg" alt="Image" class="img-fluid" style="background-color: #b2fcff;"  data-toggle="modal" data-target="#exampleModalCenter">

            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-md  modal-dialog-centered" role="document">
        <div class="modal-content rounded-0">
          <div class="modal-body py-0">

            
            <div class="d-block main-content">
              <img src="images/undraw_updated_rr85.svg" alt="Image" class="img-fluid" style="background-color: #b2fcff;">
              <div class="content-text p-4">
                
                <h3 class="mb-4">Introducing Work from Anywhere</h3>
                <p class="mb-4">All their equipment and instruments are alive. The sky was this is cloudless and of a deep dark blue. A shining crescent far beneath the flying vessel.</p>
                <div class="d-flex">
                  <div class="ml-auto">
                    <a href="#" class="btn btn-link" data-dismiss="modal">No thanks</a>
                    <a href="#" class="btn btn-primary px-4">Get the app</a>
</div>
<!-- Portfolio item 6 modal popup-->
<div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="close-modal" data-bs-dismiss="modal"><img src="assets/img/close-icon.svg" alt="Close modal" /></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="modal-body">
                            <!-- Project details-->
                            <h2 class="text-uppercase">Project Name</h2>
                            <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                            <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/6.jpg" alt="..." />
                            <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
                            <ul class="list-inline">
                                <li>
                                    <strong>Client:</strong>
                                    Window
                                </li>
                                <li>
                                    <strong>Category:</strong>
                                    Photography
                                </li>
                            </ul>
                            <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                <i class="fas fa-xmark me-1"></i>
                                Close Project
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


        

    <script src="./assets/js/jquery-3.3.1.min.js"></script>
    <script src="./assets/js/bootstrap.min.js"></script>
    <script src="./assets/js/main.js"></script>
  </body>
