<style>
  /* .img-fluid {
    width: 400px;
    padding: 0px;

  }

  .row {
    display: grid;



    grid-template-columns: repeat(2, 1fr);
  } */
</style>


<section class="page-section bg-light" id="services">
  <div class="container">
    <div class="text-center">
      <h2 class="section-heading text-uppercase">Services</h2>
      <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
    </div>
    <div class="row">
      <div class="col-lg-4 col-sm-6 mb-4">
        <!-- services item 1-->
        <div class="services-item">
          <a class="services-link" data-toggle="modal" data-target="#servicesModal1">

            <img class="img-fluid" src="assets/img/portfolio/1.jpg" alt="..." />
          </a>
          <div class="services-caption">
            <div class="services-caption-heading">Threads</div>
            <div class="services-caption-subheading text-muted">Illustration</div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6 mb-4">
        <!-- services item 2-->
        <div class="services-item">
          <a class="services-link" data-toggle="modal" data-target="#servicesModal2">

            <img class="img-fluid" src="assets/img/portfolio/2.jpg" alt="..." />
          </a>
          <div class="services-caption">
            <div class="services-caption-heading">Explore</div>
            <div class="services-caption-subheading text-muted">Graphic Design</div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6 mb-4">
        <!-- services item 3-->
        <div class="services-item">
          <a class="services-link" data-toggle="modal" data-target="#servicesModal3">

            <img class="img-fluid" src="assets/img/portfolio/3.jpg" alt="..." />
          </a>
          <div class="services-caption">
            <div class="services-caption-heading">Finish</div>
            <div class="services-caption-subheading text-muted">Identity</div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6 mb-4 mb-lg-0">
        <!-- services item 4-->
        <div class="services-item">
          <a class="services-link" data-toggle="modal" data-target="#servicesModal4">

            <img class="img-fluid" src="assets/img/portfolio/4.jpg" alt="..." />
          </a>
          <div class="services-caption">
            <div class="services-caption-heading">Lines</div>
            <div class="services-caption-subheading text-muted">Branding</div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6 mb-4 mb-sm-0">
        <!-- services item 5-->
        <div class="services-item">
          <a class="services-link" data-toggle="modal" data-target="#servicesModal5">

            <img class="img-fluid" src="assets/img/portfolio/5.jpg" alt="..." />
          </a>
          <div class="services-caption">
            <div class="services-caption-heading">Southwest</div>
            <div class="services-caption-subheading text-muted">Website Design</div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <!-- services item 6-->
        <div class="services-item">
          <a class="services-link" data-toggle="modal" data-target="#servicesModal6">

            <img class="img-fluid" src="assets/img/portfolio/6.jpg" alt="..." />
          </a>
          <div class="services-caption">
            <div class="services-caption-heading">Window</div>
            <div class="services-caption-subheading text-muted">Photography</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>



<!-- services Modals-->
<!-- services item 1 modal popup-->
<div class="services-modal modal fade" id="servicesModal1" tabindex="-1" role="dialog"  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-bs-dismiss="modal"><i class="fas fa-xmark me-1"></i></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div class="modal-body">
              <!-- Project details-->
              <h2 class="text-uppercase">Project Name</h2>
              <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
              <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/1.jpg" alt="..." />
              <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
              <ul class="list-inline">
                <li>
                  <strong>Client:</strong>
                  Threads
                </li>
                <li>
                  <strong>Category:</strong>
                  Illustration
                </li>
              </ul>
              <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                <i class="fas fa-xmark me-1"></i>
                Close Project
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- services item 2 modal popup-->
<div class="services-modal modal fade" id="servicesModal2" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-bs-dismiss="modal"><i class="fas fa-xmark me-1"></i></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div class="modal-body">
              <!-- Project details-->
              <h2 class="text-uppercase">Project Name</h2>
              <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
              <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/2.jpg" alt="..." />
              <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
              <ul class="list-inline">
                <li>
                  <strong>Client:</strong>
                  Explore
                </li>
                <li>
                  <strong>Category:</strong>
                  Graphic Design
                </li>
              </ul>
              <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                <i class="fas fa-xmark me-1"></i>
                Close Project
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- services item 3 modal popup-->
<div class="services-modal modal fade" id="servicesModal3" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-bs-dismiss="modal"><i class="fas fa-xmark me-1"></i></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div class="modal-body">
              <!-- Project details-->
              <h2 class="text-uppercase">Project Name</h2>
              <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
              <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/3.jpg" alt="..." />
              <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
              <ul class="list-inline">
                <li>
                  <strong>Client:</strong>
                  Finish
                </li>
                <li>
                  <strong>Category:</strong>
                  Identity
                </li>
              </ul>
              <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                <i class="fas fa-xmark me-1"></i>
                Close Project
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- services item 4 modal popup-->
<div class="services-modal modal fade" id="servicesModal4" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-bs-dismiss="modal"><i class="fas fa-xmark me-1"></i></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div class="modal-body">
              <!-- Project details-->
              <h2 class="text-uppercase">Project Name</h2>
              <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
              <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/4.jpg" alt="..." />
              <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
              <ul class="list-inline">
                <li>
                  <strong>Client:</strong>
                  Lines
                </li>
                <li>
                  <strong>Category:</strong>
                  Branding
                </li>
              </ul>
              <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                <i class="fas fa-xmark me-1"></i>
                Close Project
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- services item 5 modal popup-->
<div class="services-modal modal fade" id="servicesModal5" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-bs-dismiss="modal"><i class="fas fa-xmark me-1"></i></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div class="modal-body">
              <!-- Project details-->
              <h2 class="text-uppercase">Project Name</h2>
              <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
              <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/5.jpg" alt="..." />
              <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
              <ul class="list-inline">
                <li>
                  <strong>Client:</strong>
                  Southwest
                </li>
                <li>
                  <strong>Category:</strong>
                  Website Design
                </li>
              </ul>
              <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                <i class="fas fa-xmark me-1"></i>
                Close Project
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- services item 6 modal popup-->
<div class="services-modal modal fade" id="servicesModal6" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-bs-dismiss="modal"><i class="fas fa-xmark me-1"></i></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div class="modal-body">
              <!-- Project details-->
              <h2 class="text-uppercase">Project Name</h2>
              <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
              <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/6.jpg" alt="..." />
              <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
              <ul class="list-inline">
                <li>
                  <strong>Client:</strong>
                  Window
                </li>
                <li>
                  <strong>Category:</strong>
                  Photography
                </li>
              </ul>
              <button class="btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" >
                <i class="fas fa-xmark me-1"></i>
                Close Project
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>